apiVersion: "nodemanager.aldunelabs.com/v1alpha1"
kind: "ManagedNode"
metadata:
  name: "desktop-ca-k8s-master-02"
spec:
  nodegroup: desktop-ca-k8s
  controlPlane: true
  allowDeployment: false
  vcpus: 4
  memorySizeInMb: 4096
  diskSizeInMb: 20480
  labels:
  - demo-label.aldunelabs.com=demo
  - sample-label.aldunelabs.com=sample
  annotations:
  - demo-annotation.aldunelabs.com=demo
  - sample-annotation.aldunelabs.com=sample
  networks:
    -
      vnet: vmnet4
      type: custom
      device: vmxnet3
      address: 10.0.0.21
      netmask: 255.255.255.0
      gateway: 10.0.0.1
    -
      vnet: vmnet2
      type: custom
      device: vmxnet3
      address: 192.168.1.21
      netmask: 255.255.255.0
