apiVersion: "nodemanager.aldunelabs.com/v1alpha1"
kind: "ManagedNode"
metadata:
  name: "desktop-ca-k8s-managed-01"
spec:
  nodegroup: desktop-ca-k8s
  controlPlane: false
  allowDeployment: false
  vcpus: 2
  memorySizeInMb: 2048
  diskSizeInMb: 10240
  labels:
  - demo-label.aldunelabs.com=demo
  - sample-label.aldunelabs.com=sample
  annotations:
  - demo-annotation.aldunelabs.com=demo
  - sample-annotation.aldunelabs.com=sample
  networks:
    -
      vnet: vmnet4
      type: custom
      device: vmxnet3
      address: 10.0.0.80
      netmask: 255.255.255.0
      gateway: 10.0.0.1
    -
      vnet: vmnet2
      type: custom
      device: vmxnet3
      address: 192.168.1.80
      netmask: 255.255.255.0
---
apiVersion: "nodemanager.aldunelabs.com/v1alpha1"
kind: "ManagedNode"
metadata:
  name: "desktop-ca-k8s-managed-02"
spec:
  nodegroup: desktop-ca-k8s
  controlPlane: false
  allowDeployment: false
  vcpus: 2
  memorySizeInMb: 2048
  diskSizeInMb: 10240
  labels:
  - demo-label.aldunelabs.com=demo
  - sample-label.aldunelabs.com=sample
  annotations:
  - demo-annotation.aldunelabs.com=demo
  - sample-annotation.aldunelabs.com=sample
  networks:
    -
      vnet: vmnet4
      type: custom
      device: vmxnet3
      address: 10.0.0.81
      netmask: 255.255.255.0
      gateway: 10.0.0.1
    -
      vnet: vmnet2
      type: custom
      device: vmxnet3
      address: 192.168.1.81
      netmask: 255.255.255.0
---
apiVersion: "nodemanager.aldunelabs.com/v1alpha1"
kind: "ManagedNode"
metadata:
  name: "desktop-ca-k8s-managed-03"
spec:
  nodegroup: desktop-ca-k8s
  controlPlane: false
  allowDeployment: false
  vcpus: 2
  memorySizeInMb: 2048
  diskSizeInMb: 10240
  labels:
  - demo-label.aldunelabs.com=demo
  - sample-label.aldunelabs.com=sample
  annotations:
  - demo-annotation.aldunelabs.com=demo
  - sample-annotation.aldunelabs.com=sample
  networks:
    -
      vnet: vmnet4
      type: custom
      device: vmxnet3
      address: 10.0.0.82
      netmask: 255.255.255.0
      gateway: 10.0.0.1
    -
      vnet: vmnet2
      type: custom
      device: vmxnet3
      dhcp: true
      use-dhcp-routes: false
