apiVersion: "nodemanager.aldunelabs.com/v1alpha1"
kind: "ManagedNode"
metadata:
  name: "desktop-imac-k3s-managed-01"
spec:
  nodegroup: desktop-imac-k3s
  controlPlane: false
  allowDeployment: false
  vcpus: 2
  memorySizeInMb: 2048
  diskSizeInMb: 10240
  labels:
  - demo-label.aldunelabs.com=demo
  - sample-label.aldunelabs.com=sample
  annotations:
  - demo-annotation.aldunelabs.com=demo
  - sample-annotation.aldunelabs.com=sample
  networks:
    -
      vnet: vmnet8
      device: vmxnet3
      address: 192.168.172.80
      netmask: 255.255.255.0
      gateway: 192.168.172.2
    -
      vnet: vmnet1
      device: vmxnet3
      address: 172.16.251.80
      netmask: 255.255.255.0
---
apiVersion: "nodemanager.aldunelabs.com/v1alpha1"
kind: "ManagedNode"
metadata:
  name: "desktop-imac-k3s-managed-02"
spec:
  nodegroup: desktop-imac-k3s
  controlPlane: false
  allowDeployment: false
  vcpus: 2
  memorySizeInMb: 2048
  diskSizeInMb: 10240
  labels:
  - demo-label.aldunelabs.com=demo
  - sample-label.aldunelabs.com=sample
  annotations:
  - demo-annotation.aldunelabs.com=demo
  - sample-annotation.aldunelabs.com=sample
  networks:
    -
      vnet: vmnet8
      device: vmxnet3
      address: 192.168.172.81
      netmask: 255.255.255.0
      gateway: 192.168.172.2
    -
      vnet: vmnet1
      device: vmxnet3
      address: 172.16.251.81
      netmask: 255.255.255.0
---
apiVersion: "nodemanager.aldunelabs.com/v1alpha1"
kind: "ManagedNode"
metadata:
  name: "desktop-imac-k3s-managed-03"
spec:
  nodegroup: desktop-imac-k3s
  controlPlane: false
  allowDeployment: false
  vcpus: 2
  memorySizeInMb: 2048
  diskSizeInMb: 10240
  labels:
  - demo-label.aldunelabs.com=demo
  - sample-label.aldunelabs.com=sample
  annotations:
  - demo-annotation.aldunelabs.com=demo
  - sample-annotation.aldunelabs.com=sample
  networks:
    -
      vnet: vmnet8
      device: vmxnet3
      address: 192.168.172.83
      netmask: 255.255.255.0
      gateway: 192.168.172.2
    -
      vnet: vmnet2
      device: vmxnet3
      dhcp: true
      use-dhcp-routes: false
